In [1]:
#SOLUTION A.

import numpy as np
ax = np.array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41,42,43,44,45]])

rows = [[1,3],[2,2]]
cols = [[2,1],[3,0]]
ax[rows,cols]

array([[23, 42],
       [34, 31]])

In [2]:
np.array([
    [ax[1,2],ax[3,1]],
    [ax[2,3],ax[2,0]]
])

array([[23, 42],
       [34, 31]])

In [3]:
#SOLUTION B.
#column sums: 
print(ax.sum(axis=0))
#row sums: 
print(ax.sum(axis=1))

[104 108 112 116 120]
[ 65 115 165 215]


In [4]:
#SOLUTION C
ax.reshape(ax.size)[np.random.choice(ax.size,4,replace=False)]

array([45, 14, 41, 23])

In [5]:
np.array(
    [
        np.random.choice(ax[0]),
        np.random.choice(ax[1]),
        np.random.choice(ax[2]),
        np.random.choice(ax[3])
    ]
)

array([12, 25, 33, 45])

In [58]:
import pandas as pd
# 1
price_file = "AAPL_prices.csv"
# 2
data = pd.read_csv(price_file,index_col='Date',parse_dates=True)
# 3
data = data['Adj Close'].resample("BY").apply({'Adj Close':'last'})
# 4
data['y2y_change'] = data['Adj Close'].pct_change()
# 5
data['profit'] = data['y2y_change']*10000
# 6
strat_1 = data['profit'].sum()
# 7
strat_2 = (data['Adj Close'].values[-1]-data['Adj Close'].values[0]) * 10000

strat_1,strat_2


(145806.7026266998, 1727619.62)

In [30]:
import pandas as pd
import numpy as np
price_file = "AAPL_prices.csv"
df = pd.read_csv(price_file,index_col="Date",parse_dates=True)
df_year = df["Adj Close"].resample("BY").apply({"Adj Close":"last"})
df_year['pct_change'] = df_year["Adj Close"].pct_change()
df_year["profit"] = 10000*df_year["pct_change"]
buy_and_sell_profit = df_year["profit"].sum()
last = df_year["Adj Close"].iloc[-1]
first = df_year["Adj Close"].iloc[0]
profit = (last-first)*10000
buy_and_hold_profit = (last-first)*10000

print(buy_and_sell_profit,buy_and_hold_profit)

145806.7026266998 1727619.62


In [59]:
#SOLUTION

data_from_api = {"NUM_ACCESSES": 17,
"RESULT": [{"Amount": 300000, "LoanId": "001", "Name": "John"},
{"Amount": "40000", "LoanId": "002", "Name": "Jill"},
{"Amount": "240000", "LoanId": "003", "Name": "John"},
{"Amount": "480000", "LoanId": "004", "Name": "Qing"},
{"Amount": "120000", "LoanId": "005", "Name": "Jill"}],
"STATUS": "OK"}

def biggest_debtor(data_from_api):
    import pandas as pd
    df = pd.DataFrame(data_from_api['RESULT'])
    df['Amount'] = df['Amount'].astype(int)
    grouping = df.groupby('Name')
    name = grouping.sum().idxmax()['Amount']
    dollars = grouping.sum().max()['Amount']
    return (name,dollars)

biggest_debtor(data_from_api)

('John', 540000)

In [62]:
# convert to dataframe 
data = pd.DataFrame(data = data_from_api['RESULT'])
# convert string to int
data['Amount'] = data['Amount'].astype('int')
# group by name, aggregate by amount
name = data.groupby('Name').agg({'Amount':['sum']}).idxmax().values[0]
amnt = data.groupby('Name').agg({'Amount':['sum']}).max().values[0]
(name,amnt)

/var/folders/6_/yxmrw5t52wjdhykxp81bsgjw0000gn/T/ipykernel_39981/140634211.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  name = data.groupby('Name').agg({'Amount':['sum']}).idxmax()[0]


('John', 540000)

In [ ]:
#SOLUTION

import numpy as np
def append_data(ax,html_text):
    from bs4 import BeautifulSoup
    import numpy as np
    soup = BeautifulSoup(html_text,"lxml")
    items = soup.find('div',{'id':'list'}).find_all('li')
    for thing in range(1,len(items),2):
        text = items[thing].find('a').get_text()
        nums = [[float(x) for x in text.split(',')]]
        try:
            ax = np.append(ax,nums,axis=0)
        except:
            continue
    return ax

ax = np.array([[1,2,3,4,5,6],[3,2,4,5,2,3]],dtype='float')
html_text = """
<div class="bg" id="barg">
    <span class="big">List of links to follow</span>
    <span class="small">no disclaimers</span>
    <div class="bg" id="list">
        <li class="main"><a href="http://www.linksdb.com/links.html"></a></li>
        <li class="main"><a href="http://www.linksdb.com/link1.html">1,7,3,9,2,11</a></li>
        <li class="main"><a href="http://www.linksdb.com/links.html"></a></li>
        <li class="main"><a href="http://www.linksdb.com/link2.html">3,5,3,4,6,7</a></li>
        ... many more lines of data in the same format (two <li> tags for each item) ...
    </div>
</div>
"""
append_data(ax,html_text)

In [67]:
html_text = """
<div class="bg" id="barg">
    <span class="big">List of links to follow</span>
    <span class="small">no disclaimers</span>
    <div class="bg" id="list">
        <li class="main"><a href="http://www.linksdb.com/links.html"></a></li>
        <li class="main"><a href="http://www.linksdb.com/link1.html">1,7,3,9,2,11</a></li>
        <li class="main"><a href="http://www.linksdb.com/links.html"></a></li>
        <li class="main"><a href="http://www.linksdb.com/link2.html">3,5,3,4,6,7</a></li>
        ... many more lines of data in the same format (two <li> tags for each item) ...
    </div>
</div>
"""
from bs4 import BeautifulSoup
import numpy as np
soup = BeautifulSoup(html_text)
items = soup.find('div',{'id':'list'}).find_all('li')
items

[<li class="main"><a href="http://www.linksdb.com/links.html"></a></li>,
 <li class="main"><a href="http://www.linksdb.com/link1.html">1,7,3,9,2,11</a></li>,
 <li class="main"><a href="http://www.linksdb.com/links.html"></a></li>,
 <li class="main"><a href="http://www.linksdb.com/link2.html">3,5,3,4,6,7</a></li>,
 <li> tags for each item) ...
     </li>]

In [53]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                     'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
                     'value': [5, 6, 7, 8]})

df1.merge(df2, left_on='lkey', right_on='rkey')

lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  foo        5  foo        5
3  foo        5  foo        8
4  bar        2  bar        6
5  baz        3  baz        7

In [51]:
df1.join(df2.set_index(['rkey']),on='lkey',lsuffix='_caller', rsuffix='_other')

lkey  value_caller  value_other
0  foo             1            5
0  foo             1            8
1  bar             2            6
2  baz             3            7
3  foo             5            5
3  foo             5            8